### ISSUE TITLE
Entity json file

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/minecraft-data#11]
Currently we have that https://github.com/andrewrk/mineflayer/blob/master/lib/plugins/entities.js#L28
A lot of missing data compared to http://minecraft.gamepedia.com/Data_values/Entity_IDs

I propose a json like that : 
```json
{
 "10": 
   {
      "id": 10,
      "name":"Arrow",
      "type":"Projectile"
   }
}
```

It would also be possible to have one json file for every type of entity but that would be a lot of files, I think it's probably better to put everything in one file.

**Comment by rom1504** [comment]
Actually I don't think we need displayName and it's a bit annoying to get.

**Comment by Darthfett** [comment]
/Darthfett/helperbot I believe would need displayName to lookup blocks and items.  It would be good to provide the same API here, if any projects end up needing it for entities.  For example, a bot that tells you how many entities are in range (and their names).

**Comment by rom1504** [comment]
Why would you need the displayName ? Isn't the name enough ?
(5th column vs 6th column of http://minecraft.gamepedia.com/Data_values/Entity_IDs)

**Comment by rom1504** [comment]
isn't this enough https://github.com/PrismarineJS/minecraft-data/blob/master/enums/entities.json ?

**Comment by Darthfett** [comment]
I'm not even sure the original proposal would work.  It looks like the
Wither Skeletons and Skeletons are grouped as one type of entity.

**Comment by rom1504** [comment]
Well they have the same id

**Comment by rom1504** [comment]
I'm not saying this is perfect, but it's still much better than the current mineflayer thing (https://github.com/andrewrk/mineflayer/blob/master/lib/plugins/entities.js#L28)

I don't know how the game knows the difference between Wither Skeletons and Skeletons

**Comment by Darthfett** [comment]
Sounds like a similar problem as the one we are solving with blocks.  Do
entities have metadata too?  Maybe we can use a similar solution as the one
we use for blocks.

Well they have the same id

—
Reply to this email directly or view it on GitHub
<https://github.com/PrismarineJS/minecraft-data/issues/11#issuecomment-88585578>
.

**Comment by rom1504** [comment]
Hmm I don't think they have metadata (https://github.com/andrewrk/mineflayer/blob/master/lib/entity.js), maybe it's just the equipment they wear ?

**Comment by rom1504** [comment]
ok maybe entities have metadata https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/src/protocol.js#L141

the value is not in the wiki though, so I'm going to ignore it for now.

**Comment by rom1504** [comment]
some info about the metadata http://wiki.vg/Entities#Skeleton

**Comment by rom1504** [comment]
many kinds of spawn_* https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/src/protocol.js#L156 , what's an "entity" ?

**Comment by rom1504** [comment]
I added displayName in the end. I think this file is in a decent enough state to be used in mineflayer. Metadata information can be added afterwards (probably when it's done for items and blocks)

**Comment by rom1504** [comment]
I don't know if we really want to put metadata on that file. There's just the skeleton that has a simple variation.
The rest is all functional metadata that I'm not sure at all should be in that .json (see http://wiki.vg/Entities#Skeleton)

**Comment by rom1504** [comment]
So yeah indeed, entity metadata is a functional thing. It should be handle case by case in mineflayer code, not in entities.json.

File now integrated in mineflayer !
