### ISSUE TITLE
add licence

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/minecraft-data#111]
probably MIT as the rest of PrismarineJS stuff

**Comment by roblabla** [comment]
A lot of stuff in this repo doesn't actually belong to us, does it ? I don't know how copyright works though.

The extractors and other tools still need a license, but I wonder how that works for the data...

**Comment by Gjum** [comment]
this might be useful, if someone wants to read through it :D http://opendefinition.org/guide/data/

**Comment by rom1504** [comment]
What's the license of wiki.vg ? And of the mcwiki ?

**Comment by rom1504** [comment]
I guess wiki.vg "licence" is "Note: While you may use the contents of this page without restriction to create servers, clients, bots, etc… you still need to provide attribution to #mcdevs if you copy any of the contents of this page for publication elsewhere."

**Comment by rom1504** [comment]
http://minecraft.gamepedia.com/Minecraft_Wiki:Copyrights

**Comment by Gjum** [comment]
> Share Alike — If you alter, transform, or build upon this work, you may distribute the resulting work only under the same, similar or a compatible license.

So "Attribution-NonCommercial-ShareAlike 3.0" would be possible and appropriate imo

**Comment by roblabla** [comment]
NonComercial ? Please don't.

**Comment by Gjum** [comment]
commercial might violate the eula.

**Comment by roblabla** [comment]
I believe by that, they mostly mean assets and code, not data. They don't have a monopoly on a block called "stone" being mineable by a "pickaxe"...
