### ISSUE TITLE
Generating a human readable website from the data ?

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/minecraft-data#12]
It might be fun to generate something looking like http://minecraft-ids.grahamedgecombe.com/ from all the data stored in minecraft-data.
It might also get some more people interested in minecraft-data and motivated to help figure out ways to update that data.

**Comment by rom1504** [comment]
an other example http://minecraftdatavalues.com/

**Comment by rom1504** [comment]
The more complete example is of course the wiki http://minecraft.gamepedia.com/Data_values
But it might not be as user friendly as these more data-focused site.

**Comment by rom1504** [comment]
Also see, related : https://github.com/sadimusi/BurgerVitrine

**Comment by rom1504** [comment]
https://datatables.net/ is cool (see https://datatables.net/examples/ajax/simple.html)

**Comment by rom1504** [comment]
Some progress on this : click on Values in http://prismarinejs.github.io/minecraft-data
simple data display of blocks and items using datatables

**Comment by roblabla** [comment]
This looks _great_. Awesome work there :D

**Comment by rom1504** [comment]
Some improvements can still be done (maybe block/item icons, display all the blocks fields, display recipes using icons, ...) but the basic stuff is done. The rest can be handled in other issues.
