### ISSUE TITLE
Dropping legacy block/item names and using new ones ?

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/minecraft-data#13]
Current name in blocks.json and items.json are legacy names and have been changed in minecraft itself,.

I think it would it be better to replace them by the current names.
For example swordDiamond -> diamond_sword (or even minecraft:diamond_sword ?)
see http://minecraft.gamepedia.com/Data_values/Block_IDs

That means changing bots using these names

**Comment by rom1504** [comment]
The "new" names are the one you see in /give and /fill and f3

**Comment by Gjum** [comment]
+1 for `minecraft:diamond_sword`

Used in F# debug screen, in vanilla commands, compatible with modded blocks.

**Comment by wtfaremyinitials** [comment]
:+1:

**Comment by rom1504** [comment]
It might be possible to have a blockNamesVariation.json file to keep compatibility with old names.

**Comment by roblabla** [comment]
I really wish we'd keep the old names around just for compatiblity. They should be depreciated in favor of the new ones, but still kept around.

**Comment by rom1504** [comment]
@roblabla mineflayer uses minecraft-data for these names.
That means I need to store the old names somewhere. (that would be better in minecraft data I guess, but I don't really like the idea of a old_items_names.json file)

**Comment by rom1504** [comment]
So, in conclusion : the look up by name was not really in mineflayer ago since not long ago, so changing the names doesn't really break any API.
So I'll just change the names, we don't need the old ones (and anyway they are not lost, thanks git).
