### ISSUE TITLE
Add block drops

### ISSUE THREAD

**Issue by roblabla** [PrismarineJS/minecraft-data#15]
Currently, there's no way to know what kind of blocks drops we can have. The problem with block drops is that they depend on item used to mine, among other things. Anyway, a good start would be : 

```js
{
  "id": 1,
  "name": "stone",
  // ...
  "drops": [{ "id": 4, "minAmount": 1, "maxAmount": 1 }]
}
```

The problem with the above : it doesn't take into account tool used to mine. Not too sure how to make the schema not too fugly otherwise...

How does this sound ?

**Comment by rom1504** [comment]
I'm okay with that (it's even automatically extractable from the wiki : see drops in the infobox in http://minecraft.gamepedia.com/Stone).
The tool you need to use is an other field (harvestTools).

Why minAmount and maxAmount though ? Isn't amount enough ?

**Comment by roblabla** [comment]
Glowstone, lapis, etc... both have random amount of drops.

**Comment by Gjum** [comment]
This could also be done for entities.

**Comment by rom1504** [comment]
Oh right, yeah.

**Comment by rom1504** [comment]
Tools drop all drop the same thing (or nothing) for one given block, except for tools with enchantments : 
* silk
* fortune

Enchantments (http://minecraft.gamepedia.com/Enchant#Enchantments) should probably be handled separately.

**Comment by Gjum** [comment]
There is a lot of `minCount: 1, maxCount: 1` - should we allow a simple `count: 1` if `min == max`?

**Comment by rom1504** [comment]
Yeah I guess.
Oh and I took the "chance" from the wiki when it was available, to minCount can be a number from 0 to 1 (for exemple 0.3333 for 33.33%), I don't know if it that's a good idea.

**Comment by roblabla** [comment]
chance might be useful for servers to implement the dropping behavior ;)

**Comment by rom1504** [comment]
So : there are a lot of minCount: x, maxCount: y with x==y, we can add a count: field. Because often x==y==1, it might also be possible to not put a count at all for these ? (default : cound = 1)

**Comment by roblabla** [comment]
Wouldn't it be better to keep data difference to a minimum ? I feel having either min/max OR count would make it harder to use the minecraft-data without really adding value.

**Comment by rom1504** [comment]
Yeah I agree.
What about having the default value for both these fields to 1 so in most cases they just wouln't be there ?

**Comment by roblabla** [comment]
Yeah, default values are perfectly fine.
