### ISSUE TITLE
enchantment data is missing

### ISSUE THREAD

**Issue by plexigras** [PrismarineJS/minecraft-data#153]
https://gist.github.com/plexigras/95dbf1b28dcfb50d094cf6870c392524

**Comment by Gjum** [comment]
used here https://github.com/PrismarineJS/mineflayer/pull/453/files/cfc12b852602079cd63c3d6cf3b9018c3f203bcf#diff-313c742a638c4158cb20db1a18f89308R189

**Comment by rom1504** [comment]
Oh indeed I forgot about this. @plexigras do you have an extractor for this ?

**Comment by plexigras** [comment]
just quickly wrote one:
https://gist.github.com/542490f66c6e4dc18994167ec34d6c2a
