### ISSUE TITLE
1.11 changes to entities

### ISSUE THREAD

**Issue by Pokechu22** [PrismarineJS/minecraft-data#155]
* `Mob` and `Monster` don't exist any more
* IDs are lowercase and namespaced, and some changed (`minecraft:tnt` vs `PrimedTnt`)
* There are no objects with ID 11 and 12 any more (and that hasn't been the case for a while, I think)
    * All minecarts use ID 10, so that's going to need to be represented some way (it's specified in the object data)
* Some sizes are wrong
* Horses!  You're missing the different types of horses...  and `EntityHorse` is no more (even with legacy names); it's `Horse` now.

**Comment by rom1504** [comment]
I didn't extract the 1.11 entities file at all yet actually.

It is extracted using both mcwiki and wiki.vg, I'll do it. (hopefully http://wiki.vg/Entities is up to date)

(using https://github.com/PrismarineJS/node-minecraft-extractor )

**Comment by rom1504** [comment]
I believe this is all fixed. see https://github.com/PrismarineJS/minecraft-data/blob/master/data/pc/1.11/entities.json
