### ISSUE TITLE
skeleton horses are missing

### ISSUE THREAD

**Issue by plexigras** [PrismarineJS/minecraft-data#157]
https://prismarinejs.github.io/minecraft-data/?d=entities
http://minecraft.gamepedia.com/Data_values/Entity_IDs

**Comment by rom1504** [comment]
is that a 1.11 thing ?

**Comment by rom1504** [comment]
Well anyway, I didn't extract the 1.11 data, should do that.
Related to #155

**Comment by plexigras** [comment]
http://wiki.vg/Protocol_History#16w32a
> Zombies, skeletons, and horses have been split into their component entities rather than having a Type field (although the Type field still exists on Zombies, it is unused).

**Comment by plexigras** [comment]
i found this because in the current npm version(2.0.0 but not in git master) mineflayer crashes

so might wanna push that to npm

**Comment by rom1504** [comment]
No the 1.11 data is not even in mcdata yet.
However, you could try the last commit of mineflayer, it should prevent crash due to entities ;)

**Comment by rom1504** [comment]
fixed https://github.com/PrismarineJS/minecraft-data/blob/master/data/pc/1.11/entities.json#L272
