### ISSUE TITLE
Possible map between names used in protocol.json and actual packet names.

### ISSUE THREAD

**Issue by chibill** [PrismarineJS/minecraft-data#160]
There are large differences in the names of packets in protocol.json and everywhere else.
For example Chunk data is for some reason named map_chunk which could be confused with map.

Also there are a few others that just seem odd.

Also including the packet ids might be a good idea.

**Comment by rom1504** [comment]
Actual packet names are unknown but see #27

**Comment by chibill** [comment]
Well considering you use wiki.vg any how you can at least match them....

**Comment by rom1504** [comment]
the packet id is in the protocol.json https://github.com/PrismarineJS/minecraft-data/blob/master/data/pc/1.11/protocol.json#L298

**Comment by rom1504** [comment]
There are reasons to use protocollib names or wiki.vg names, and they are difficulties in changing everything now, but read #27, everything is already said there. Having an additional file to provide other names would be ok for example.

**Comment by chibill** [comment]
As for what you refranced wiki.vg names are the standard way to name the MC packets for divating then makes it hard to use.

Also it strange that the id to name mapping is not actually with the packet but hidden away in the file somewhere else.

**Comment by rom1504** [comment]
> As for what you refranced wiki.vg names are the standard way to name the MC packets for divating then makes it hard to use.

Are they ? ProtocolLib (which is what our names are based on) use different names.

> Also it strange that the id to name mapping is not actually with the packet but hidden away in the file somewhere else.

protocol.json follows https://github.com/ProtoDef-io/ProtoDef/blob/master/doc/datatypes.md#mapper

It actually makes more sense protocol-wise to not put an id in the packet, because the id is not part of the type at all.
Also the ids change all the time, so it's a good thing the actual packet definition of it doesn't need to change.

Mojang doesn't even store the ids at all in their code, it's all order defined ;)

**Comment by chibill** [comment]
Protocollib is based around bukkit mappings for stuff so of course it will be different. 

Also why is the ProtoDef-io stuff so complicated like really. Also there is a broken switch on 1.11 protocol.jdon it has no name for the field it switches on.

**Comment by roblabla** [comment]
What do you find complicated in protodef ?

On March 6, 2017 7:44:19 PM GMT+01:00, William Gaylord <notifications@github.com> wrote:
>Protocollib is based around bukkit mappings for stuff so of course it
>will be different. 
>
>Also why is the ProtoDef-io stuff so complicated like really. Also
>there is a broken switch on 1.11 protocol.jdon it has no name for the
>field it switches on.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/PrismarineJS/minecraft-data/issues/160#issuecomment-284491143

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by chibill** [comment]
The fact that lists are used where dictanaries would have made using it
easier.

**Comment by roblabla** [comment]
If you talk about fields, there is a reason for that. Dictionaries are unordered. They cannot hold the order of the fields.

**Comment by chibill** [comment]
So order is not needed where I am talking about. Also lists are normally unordered.

**Comment by roblabla** [comment]
@chibill 

1. JSON arrays are ordered.
2. A type is defined as an array with its first field being a typename, the second being its argument. For instance, `["container", [{ name: "stuff", type: "i8" }]]`. A switch's arguments is (IIRC) an Object with two keys : `fields` and `compareTo`. `compareTo` is a reference to the field to switch against, and `fields` is another Object where the key is what to switch against, and the value is the type to read in case the switch is true.

This is defined there : https://github.com/ProtoDef-io/ProtoDef/blob/master/doc/datatypes.md#switch

ProtoDef spec is in need of some love. Unfortunately, life gets in the way.

Also, one of minecraft-data's goal is to replace wiki.vg entirely (see http://prismarinejs.github.io/minecraft-data/?d=protocol and https://github.com/roblabla/minecraft-data/tree/gh-pages-comments ).

**Comment by roblabla** [comment]
Concerning changing the names to wiki.vg names. I still have the same stance now as back in #27. We could make an entirely unnamed protodef file, and then give optional naming files. I would only support ProtocolLib naming files, but if other people want to help maintaining support with wiki.vg names, they can do so.

**Comment by chibill** [comment]
Well considering it has no information on what the data means you won't
ever replace it.  And I am going to end this. I have to manually deal with
the protocol as the ProtoDef has no python impl and I am not going to make
on as its not possible with out some internal knowledge of how the stuff
works. As the docs do not follow what is actually there.

**Comment by roblabla** [comment]
Many people have made protodef impls without internal knowledge. ProtoDef and minecraft-data was originally data we had in NMP that we exported in an external project. Since then, at least three implementations were made independently, without any help from our part (the java, haskell and elixir compilers).

Anyway, good luck on your endeavors. If you need me for any help, I'm available on gitter or here :).

**Comment by chibill** [comment]
I have found no java version and the others are part of the ProtoDef org so
are part of its project...

**Comment by roblabla** [comment]
https://github.com/Johni0702/ProtocolGen/blob/1.8/generator.gvy this is a compiler (arguably, it's not a generic protodef compiler, but a minecraft-data-specific one) written in groovy that generates java files. There's a link to it right there in the minecraft-data readme :).
