### ISSUE TITLE
Make doc default to 1.11

### ISSUE THREAD

**Issue by chibill** [PrismarineJS/minecraft-data#162]
One example is http://prismarinejs.github.io/minecraft-data/?d=protocol#toClient_map_chunk which is missing blockEntities until you pick a version. (Does not matter the version)

**Comment by chibill** [comment]
Nvm it turns out the view defaults to some pre-1.10 version. Maybe have it default to the current release?

**Comment by rom1504** [comment]
yep I'll make it default to 1.11

**Comment by rom1504** [comment]
done
