### ISSUE TITLE
Minecraft update 1.12.1

### ISSUE THREAD

**Issue by DeliciousJaffa** [PrismarineJS/minecraft-data#188]
Proto Version: 338

I don't think much has changed but I'm not sure how to check or update the data properly.

**Comment by rom1504** [comment]
this http://wiki.vg/Pre-release_protocol
see https://github.com/PrismarineJS/minecraft-data/pull/180/files (also see the comments) as an example on how to update, if you feel like doing it

**Comment by DeliciousJaffa** [comment]
I'd only cause more headache if I tried myself

**Comment by DeliciousJaffa** [comment]
Submitted incomplete PR at https://github.com/PrismarineJS/minecraft-data/pull/189

**Comment by rom1504** [comment]
done
