### ISSUE TITLE
Why is buffer a native type?

### ISSUE THREAD

**Issue by ShadowLordAlpha** [PrismarineJS/minecraft-data#191]
Is there a reason for the `buffer` type being a native instead of being defined as an array? Just looking though the protocol json it seems like it could just as easily be defined as something like 

```
"buffer": [
    "array", {
        "countType": "varint",
        "type": "i8"
    }
]
```

or even not being defined at all and just replacing them all with the array type. There might be a few other that the some thing could be done to like possibly `optionalNbt` but I have not gone though everything yet

**Comment by roblabla** [comment]
We had some discussion with @hansihe and @rom1504 about this IRL. Basically, it amounts to two things : 

1. Buffer and Array potentially map to different underlying types in some languages (JS in particular, being the language protodef originally targeted, has both an array type and a special-case Buffer type)

2. They have different meanings. A byte array is really just that, an array of 8-bit-sized numbers, but `buffer` means an untyped blob of data.

**Comment by ShadowLordAlpha** [comment]
Alright that makes more sense with the different underlying types then so I guess I'll just keep working on my special case for it
