### ISSUE TITLE
Error items table in prismarinejs.github.io

### ISSUE THREAD

**Issue by gserrg** [PrismarineJS/minecraft-data#198]
http://prismarinejs.github.io/minecraft-data/?d=items The icon is displayed in a separate cell, resulting in an offset and losing the last column.
P.S. On found a repository with source code http://prismarinejs.github.io/minecraft-data/bundle.js

**Comment by roblabla** [comment]
https://github.com/PrismarineJS/minecraft-data/blob/web/showValues.js#L57

The problem is that (1) we mixed up name and id, and two: we put the image in name, but never show the raw name.

**Comment by rom1504** [comment]
fixed
