### ISSUE TITLE
Missing item (id:453) in 1.12

### ISSUE THREAD

**Issue by dexter3k** [PrismarineJS/minecraft-data#199]
Knowledge Book (id: 453) seems to be missing in 1.12, 1.12.1, 1.12.2.
https://minecraft.gamepedia.com/Knowledge_Book

**Comment by rom1504** [comment]
I guess I probably didn't run the extractor for 1.12.

I'll try to do it tonight.

If you want, you could try to run it (
https://github.com/PrismarineJS/minecraft-wiki-extractor/blob/master/bin/item_to_json.js
) and do a PR to minecraft-data.

**Comment by SMemsky** [comment]
Sorry, this is my first experience with js stuff evet. Not sure if I can really do a PR.
But I fixed my problem by adding
```
{
    "id": 453,
    "displayName": "Knowledge Book",
    "stackSize": 1,
    "name": "knowledge_book"
  },
```
To `data/pc/1.12/items.json`
