### ISSUE TITLE
1.13 support

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/minecraft-data#200]
create a 1.13 dir and : 
* [x] update protocol : 
  * last version in mcdata is 17w50a https://github.com/PrismarineJS/minecraft-data/commits/master
  * there's a bunch more versions since : http://wiki.vg/Protocol_version_numbers
  * see history between http://wiki.vg/index.php?title=Pre-release_protocol&oldid=13556 and http://wiki.vg/index.php?title=Pre-release_protocol&oldid=14150 :  http://wiki.vg/index.php?title=Pre-release_protocol&offset=&limit=150&action=history
   * update each point
* [ ] update the rest of the data

**Comment by rom1504** [comment]
I estimate work for the protocol to 2-3 hours
work for the rest is prob 1-2 hours.

if anyone is interested to help, feel free to say (and/or to create a pr with some of the work)

**Comment by lluiscab** [comment]
I'm more than up to for this work, just need to know what to do / how to do it and then have someone make sure everything is ok

**Comment by lluiscab** [comment]
As far as I can see pretty much every packet id has changed and some packets have been added. I guess there's an automatic tool to extract this data. I think I could update the protocol tomorrow morning if given the instructions to do so.

**Comment by rom1504** [comment]
The instructions are in the first post. It's not automatic.
If you want more details come talk about it on discord/gitter

**Comment by rom1504** [comment]
protocol is done.
Missing here : 
* [ ] blocks
* [ ] biomes
* [ ] effects
* [ ] enchantments
* [ ] items
* [ ] recipes
* [ ] instruments
* [ ] materials
* [ ] entities
* [ ] windows
* [ ] language

Most of these can be extracted using the existing extractors and/or the new minecraft jar generators provided by mojang.
They are required for mineflayer (and flying-squid).

**Comment by rom1504** [comment]
also see https://github.com/PrismarineJS/node-minecraft-protocol/pull/579

**Comment by rom1504** [comment]
done
