### ISSUE TITLE
1.13.1 Support

### ISSUE THREAD

**Issue by DeliciousJaffa** [PrismarineJS/minecraft-data#203]
Seems to be minor changes protocol-wise.

**394**
- Added a Hand parameter to Edit Book, to fix [MC-84005](https://bugs.mojang.com/browse/MC-84005)
- Changed the max length of the text for Tab Complete (serverbound) from 256 to 32500, to fix [MC-132663](https://bugs.mojang.com/browse/MC-132663)

**395**
- Boss Bar now has separate flags for music (0x02) and fog (0x04), rather than using 0x02 for both ([MC-123880](https://bugs.mojang.com/browse/MC-123880))

**396-401**
No changes listed

https://wiki.vg/Protocol_History

**Comment by rom1504** [comment]
done, thanks for the summary
