### ISSUE TITLE
Durability information

### ISSUE THREAD

**Issue by uncovery** [PrismarineJS/minecraft-data#212]
would it be possible to also add durability information for tools (swords etc)? Or, if not the durability in numeric terms, at least a flag if an item is affected by durability?

**Comment by lluiscab** [comment]
I doubt that burger extracts this data, [as this comment says](https://github.com/mcdevs/Burger/blob/02f9537c4f7982d14391a786509c0756e5a4a490/burger/toppings/items.py#L297) but I'm not sure and I can't really check right now.

**Comment by rom1504** [comment]
sure thanks !

**Comment by derjp** [comment]
I would also really appreciate this data. Would be a great addition!

**Comment by rom1504** [comment]
looks done for 1.14
@Sainan do you know how you got this data ?

**Comment by nickelpro** [comment]
Fixed and automated with turbo-inventor, see discussion in https://github.com/PrismarineJS/minecraft-data/pull/438
