### ISSUE TITLE
new item whit 1.13.1 or after

### ISSUE THREAD

**Issue by lintx** [PrismarineJS/minecraft-data#215]
minecraft 1.13.1 on add 5 item:
 dead_tube_coral
dead_brain_coral
dead_bubble_coral
dead_fire_coral
dead_horn_coral
itemId is 443-448
1.13.1 and 1.13.2 itemId 443-784 is error

本人英文不好，如果有语法或者哪里不对请见谅，以下是中文愿意：
自从1.13.1之后新增了5种失活的珊瑚（Corals），导致item id442以后新增了5种物品，导致442以后所有物品id都不对

**Comment by rom1504** [comment]
done
