### ISSUE TITLE
Displayname of block does not match item name

### ISSUE THREAD

**Issue by uncovery** [PrismarineJS/minecraft-data#219]
See here: 
https://github.com/PrismarineJS/minecraft-data/blob/master/data/pc/1.13/blocks.json#L245
and here:
https://github.com/PrismarineJS/minecraft-data/blob/master/data/pc/1.13/blocks.json#L229

There are more, such as Stones , saplings etc.

**Comment by rom1504** [comment]
Should it ? Does it match in minecraft ?

**Comment by rom1504** [comment]
No idea.

Anyway, don't use the display name as an id.
It's not an id, it's just an informative human readable text.

**Comment by uncovery** [comment]
Yeah of course not. The issue arises when I use the display name from the blocks to describe something where it references the item name from a database on a website or so and it does not make sense to whomever reads it.

**Comment by rom1504** [comment]
seems fixed
