### ISSUE TITLE
Add state range to minecraft data

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/minecraft-data#221]
We need it for prismarine-chunk.

@lluiscab if you know how to extract it easily, I would appreciate the help

I'm talking about the range at https://pokechu22.github.io/Burger/1.13.2_numeric.html

They're needed to know what block we got.

**Comment by lluiscab** [comment]
I think that one of the JSON files extracted by the mc jar contains a mapping block state -> block id.

Would have to check but I'm super busy this week and the next.

**Comment by rom1504** [comment]
done
