### ISSUE TITLE
knowledge book?

### ISSUE THREAD

**Issue by uncovery** [PrismarineJS/minecraft-data#225]
What is this knowledge_book item for 1.13.2?
I am not sure that belongs there: https://github.com/PrismarineJS/minecraft-data/blob/master/data/pc/1.13.2/items.json#L4634

**Comment by plexigras** [comment]
https://lmddgtfy.net/?q=!mcw%20Knowledge%20Book

**Comment by uncovery** [comment]
oops, sorry!
