### ISSUE TITLE
Bedrock edition names are used on PC edition blocks?

### ISSUE THREAD

**Issue by Mstrodl** [PrismarineJS/minecraft-data#238]
For some reason, blocks like `double_plant`, `grass`, and `leaves` are in the PC data files (1.12.2) even though those blocks are only in bedrock edition. Why is this, and what can be done about it?

**Comment by rom1504** [comment]
it's due to the wiki extractor that didn't differentiate
maybe we could run the burger extractor for this version

**Comment by nickelpro** [comment]
`double_plant`, `grass`, and `leaves` are all blocks that exist in Java MC as well, so I'm not sure what this bug was ever about. Closing, if there's a specific thing I'm missing we can re-open.

**Comment by Mstrodl** [comment]
I would look again, but I really can't be bothered and I gave up on my project long ago... TL;DR is that the names didn't match the names used in PC edition resource packs iirc

**Comment by nickelpro** [comment]
How could 1.12.2 not match datapacks? It predates the introduction of datapacks

**Comment by Mstrodl** [comment]
I didn't say datapacks, I said resource packs
