### ISSUE TITLE
Why pc/common/versions.json?

### ISSUE THREAD

**Issue by timmyRS** [PrismarineJS/minecraft-data#240]
I understand that pc/common/protocolVersions.json contains all protocol versions, regardless of inclusion in minecraft-data. However, pc/common/versions.json only contains versions included in minecraft-data. Isn't this pointless as the same data can be obtained by taking all keys in dataPaths.json's "pc" object?

**Comment by rom1504** [comment]
Yeah we could do that indeed (use the keys of loadpath and remove common/versions)
