### ISSUE TITLE
items.json: stackSize is incorrectly 64 for all tools and weapons

### ISSUE THREAD

**Issue by MestreLion** [PrismarineJS/minecraft-data#254]
All Shovels, Swords, Pickaxes, Bow, etc are being reported as having `stackSize = 64`. Like any items with durability their stackSize should be 1.

Speaking of durability... is there a way this information is included somewhere?

**Comment by MestreLion** [comment]
Items with incorrect stackSize, as of `pc/1.14`:
```
bow
carrot_on_a_stick
diamond_axe
diamond_hoe
diamond_pickaxe
diamond_shovel
diamond_sword
elytra
fishing_rod
flint_and_steel
golden_axe
golden_hoe
golden_pickaxe
golden_shovel
golden_sword
iron_axe
iron_hoe
iron_pickaxe
iron_shovel
iron_sword
shears
shield
stone_axe
stone_hoe
stone_pickaxe
stone_shovel
stone_sword
wooden_axe
wooden_hoe
wooden_pickaxe
wooden_shovel
wooden_sword
```

**Comment by timmyRS** [comment]
Durability is the metadata of the item pre-flattening (0-255), and post-flattening I think it's stored as the "Damage" short. Also, if you want you can open a PR to fix this, otheriwse, I could do it later.

**Comment by MestreLion** [comment]
Thanks for such a quick fix, @timmyRS !

About durability: I don't mean the current damage on a particular _item_, I mean the _total durability_ of an item _type_, sometimes referred as "max damage". For example, 1561 for all Diamond Tools, 384 for the Bow, 64 for a Fishing Rod, etc. This is a nice-to-have information on a project that aims to have all minecraft items and blocks data.

**Comment by timmyRS** [comment]
Ah, unfortunately not, altough I think you could rather quickly scrape the wiki for that, and maybe create a PR.
