### ISSUE TITLE
Block Collision Boxes

### ISSUE THREAD

**Issue by Gjum** [PrismarineJS/minecraft-data#258]
Minecraft-Data should provide collision box data for each block.

A use case is implementing client physics or server entity pathfinding, for example https://github.com/PrismarineJS/mineflayer/issues/228 or https://github.com/Gjum/Botlin/issues/4.

This might go together with #52 and/or #83 but since the collision box data is so much it might be better to keep it in a separate file.

**Comment by Gjum** [comment]
I've been playing around with extracting collision box data for [1.14.4](https://gist.github.com/Gjum/ab34ac5b50085dbce4991e09623b0f60) and [1.15](https://gist.github.com/Gjum/4a4084097b10e8384526d8ee7e6d3c98) today and came up with this data format as a compromise between file size and consumer implementation simplicity:
```js
{
  "blocks": {
    blockId: shape, // all block states have same shape
    blockId: [ shape, ... ], // at least one state shape different from others; indexed by stateId
    ...
  },
  "shapes": { shapeId: [[xMin,yMin,zMin, xMax,yMax,zMax], ...] },
}
```
The [extractor](https://github.com/Gjum/McDataExtracting/blob/master/src/main/java/mcextract/Main.java#L57) is based on [Fabric client mod API](https://fabricmc.net/) and also includes a [sample implementation](https://github.com/Gjum/McDataExtracting/blob/master/src/main/java/mcextract/BlockCollisionBoxStorage.java) of how to consume the JSON and provide a `Shape getBlockShape(String blockId, int blockStateId)` method (the returned `Shape` is a collection of cuboids).

**Comment by nickelpro** [comment]
+1 for this, I'm consuming a lot of minecraft-data with [mcd2c](https://github.com/SpockBotMC/mcd2c) and having some sort of easily consumable model data is going to be next on my list. The proposed json format is simple enough to translate into to a binary mesh so it works for me.

**Comment by rom1504** [comment]
This seems pretty good indeed

**Comment by Gjum** [comment]
Extracting 1.12.2 blocks was a bit tricky but it's done now ([source](https://github.com/Gjum/McDataExtracting/tree/1.12.2)), and personally I don't need any data older than that.

1.12.2 and older versions have the downside that collision boxes for a block of given (id:meta) additionally depend on adjacent blocks (e.g., cobblestone walls change their collision box if there's a solid block to N/S/E/W/above), so this dataset assumes the block is surrounded by air; this is the best that I can do without encoding the full logic for these special cases somehow.

If you consider this useful I can open a PR with the 1.12.2, 1.14.4, and 1.15 collision boxes as linked [in the first comment](https://github.com/PrismarineJS/minecraft-data/issues/258#issuecomment-565585781). Do you need a schema to go with that?

**Comment by timmyRS** [comment]
A valid schema would be needed for the tests to succeed, but just providing the data would be nice, someone else can take care of the schema. ;P

**Comment by rom1504** [comment]
Yeah it would be useful
