### ISSUE TITLE
Inconsistencies in availability of some files.

### ISSUE THREAD

**Issue by wgaylord** [PrismarineJS/minecraft-data#260]
Seems that sometimes there will be files missing from a PC versions folder. For example 1.14 does not contain a blocks json file.

1.14 is missing.
- enchantments
- blocks
- instruments
- materials
- windows

I am guessing it just hasn't been gotten around to being updated yet. 

I think it might be a good idea to look into making a program to automatically update them.

**Comment by timmyRS** [comment]
If you're just looking for the data, it might be worth mentioning the [Data Generators](https://wiki.vg/Data_Generators) from 1.13 snapshot 18w01a which provide the data you're looking for, just in a different format. Also, you can find all of it at [https://apimon.de/mcdata/](https://apimon.de/mcdata/).

**Comment by wgaylord** [comment]
It was mentioned in another issue that there is more data in these then in the ones from the Data Generators. Is this no longer true?

**Comment by timmyRS** [comment]
There certainly is more data in this project than what the Data Generators will give you, but depending on what you're trying to do, the Data Generators can either fully provide what you need, or be used in combination with minecraft-data by cross-referencing with older data.

**Comment by rom1504** [comment]
We have a bunch of different extractors from different sources. See the
readme.
Nobody has gotten around to run them for newer versions but you're welcome
to do it !

**Comment by rom1504** [comment]
done
