### ISSUE TITLE
1.15.2 not available through NPM

### ISSUE THREAD

**Issue by harrego** [PrismarineJS/minecraft-data#261]
I saw that 1.15.2 was added to the project in commit a057680 but it doesn't appear to be available through NPM or on the [node-minecraft-protocol](https://github.com/PrismarineJS/node-minecraft-protocol) project yet. Is there more to be added for 1.15.2 and will it be updated soon?

Aside from that thanks for all the great work you do!

**Comment by rom1504** [comment]
protocol is not added yet, I can add it though.
I'm always curious as to what are people using the very last version (out 3 days ago) for ?

**Comment by harrego** [comment]
My case is a small vanilla server with a few friends

**Comment by timmyRS** [comment]
Commit  a057680 simply added 1.15.2 to the list of Minecraft versions, but that doesn't mean any data for it is available yet.

**Comment by Mstrodl** [comment]
@rom1504 Any news on protocol support? It's nicer to not have to tell people to downgrade the client to connect..

**Comment by timmyRS** [comment]
1.15 and 1.15.1 already have protocol.json files available:
- https://github.com/PrismarineJS/minecraft-data/tree/master/data/pc/1.15
- https://github.com/PrismarineJS/minecraft-data/tree/master/data/pc/1.15.1

**Comment by rom1504** [comment]
Ok I'll do it then

**Comment by Mstrodl** [comment]
@timmyRS Yes, but 1.15.2 seems to have a different protocol version breaking connection support.

**Comment by timmyRS** [comment]
My project only uses 1.15's protocol.json and has no problems.

**Comment by Mstrodl** [comment]
@timmyRS Odd, in my case I've got both a client and sever running via `node-minecraft-protocol` and I've definitely had issues, so perhaps you just aren't using it in the same ways.

**Comment by timmyRS** [comment]
I'm using minecraft-data's protocol.json directly, without any wrappers, but I only use it to fetch packet IDs, so maybe there's something different in some packet?

**Comment by Mstrodl** [comment]
@timmyRS I think I had issues with the login packet after I forced the server to work with it, although I don't remember exactly offhand. But yes, there's different data, hence the need for a protocol version which is different between 1.15.1 and 1.15.2.

**Comment by rom1504** [comment]
I don't understand what you are talking about.
1.15.2 protocol is different from 1.15.1. there is 0 doubt about this.
I started the update, I'll finish tomorrow

**Comment by rom1504** [comment]
done
