### ISSUE TITLE
Type of 'data' field in packets 'login_plugin_request' and 'login_plugin_response' should be 'restBuffer'

### ISSUE THREAD

**Issue by Hadron67** [PrismarineJS/minecraft-data#263]
I found this issue when implementing ip forwarding for Velocity proxy using node-minecraft-protocol. Velocity uses the above two packets to send player information to downstream server. The problem is the `data` field of `login_plugin_response`, which contains player information, wasn't parsed correctly, I always got errors like 
```
Chunk size is 1123 but only 124 was read ; partial packet : {"name":"login_plugin_response","params":{"messageId":0,"success":true,"data":...
```
After checking [LoginPluginResponse.java](https://github.com/VelocityPowered/Velocity/blob/master/proxy/src/main/java/com/velocitypowered/proxy/protocol/packet/LoginPluginResponse.java) of Velocity source code I noticed the type of 'data' field is not defined correctly. I haven't checked the source code of Minecraft yet.

**Comment by rom1504** [comment]
this seems correct.
Do you mind making a PR ?

**Comment by nickelpro** [comment]
Def a bug, I'll fix it. Do we want [the response buffer](https://wiki.vg/Protocol#Login_Plugin_Response) to be inside a true/false switch or just let it be an empty buffer when `Successful` is False?

**Comment by rom1504** [comment]
you can use the option type to encode that boolean, the buffer will be absent if false

**Comment by nickelpro** [comment]
The option is a little weird, because it makes it awkward to send back a "Plugin request successful, but I have no response data" type packet. But absent a demonstrated use case for that I'm not going to worry about it

**Comment by rom1504** [comment]
thanks
