### ISSUE TITLE
software license?

### ISSUE THREAD

**Issue by ConradP** [PrismarineJS/minecraft-data#266]
This is a really neat project and I would love to use it as a component for one of my projects, but I don't see any licensing information stored in the source code : (   

could you please consider adding a [License](https://help.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository) to your project so I (and other potential contributers) know how we can use this project?

**Comment by timmyRS** [comment]
The README says the license is MIT: https://github.com/PrismarineJS/minecraft-data#license

**Comment by rom1504** [comment]
indeed
