### ISSUE TITLE
Use countType in array to reduce field count

### ISSUE THREAD

**Issue by roblabla** [PrismarineJS/minecraft-data#28]
Example : 

```json
{
  "name": "chunkDataLength",
  "type": "count",
  "typeArgs": {
    "type": "varint",
    "countFor": "chunkData"
  }
},
{
  "name": "chunkData",
  "type": "buffer",
  "typeArgs": {
    "count": "chunkDataLength"
  }
}
```

should become
```json
{
  "name": "chunkData",
  "type": "buffer",
  "typeArgs": {
    "countType": "varint"
  }
}
```

This greatly simplifies the protocol.json file, and makes it more obvious that count fields should not be supplied on write. I went over the 1.8 protocol, there are no instances where the count field is far away from the data it counts.

**Comment by rom1504** [comment]
Sounds good, doing the .json transformation itself should be fairly easy, I think I'll do it and put it in a minecraft-data branch so we can see how to implement this in node-minecraft-protocol.

**Comment by rom1504** [comment]
done
