### ISSUE TITLE
food.json

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/minecraft-data#295]
https://minecraft.gamepedia.com/Food parsing this and putting it in a food.json

Would make it easier to code bot that can eat

**Comment by AppDevMichael** [comment]
What would one do for when there are two Suspicious Stews, how could I differentiate them in the json?

Current format that I have come up with:
```js
  {
    id: 576,
    displayName: 'Apple',
    name: 'apple',
    stackSize: 64,
    foodPoints: 4,
    saturation: 2.4,
    effectiveQuality: 6.4,
    saturationRatio: 0.6
  }
```

**Comment by rom1504** [comment]
There is only one Suspicious stews. Apparently there is a special effect to take into account with it, but I'd say it doesn't belong in that file

**Comment by AppDevMichael** [comment]
What about the cake?

**Comment by rom1504** [comment]
well I guess you can always decide to put 2 names for them, and we'd have to be careful about that when using it

**Comment by rom1504** [comment]
last step https://github.com/PrismarineJS/minecraft-data/pull/302#issuecomment-653774254

**Comment by AppDevMichael** [comment]
https://github.com/PrismarineJS/node-minecraft-data/pull/37

**Comment by rom1504** [comment]
done
