### ISSUE TITLE
1.16 data

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/minecraft-data#298]
missing : 
* [x] material.json, similar to https://github.com/PrismarineJS/minecraft-data/pull/282
* [x] language.json : minecraft jar extractor has a script
* [x] collision shape : see gjum mod

cc @AppDevMichael if you're interested

BTW a script doing everything for a new version would be awesome https://github.com/PrismarineJS/minecraft-data/issues/283

**Comment by AppDevMichael** [comment]
#300 

Added all of the missing files. 

I will look into the scripting at some point.

**Comment by rom1504** [comment]
Thanks, done
