### ISSUE TITLE
New recipe format

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/minecraft-data#3]
Some cases are not handled by the recipes format, in particular a lot of thing related to metadata.
See https://github.com/PrismarineJS/minecraft-data/wiki/Recipe-format vs https://github.com/PrismarineJS/minecraft-data/wiki/Proposed-new-recipe-format
What should be done : 

* [x] finish defining the new format
  * [x] check it handles all cases
  * [x] check it isn't too ugly
* [x] see how it would be implemented in mineflayer
* [ ] update the wiki extractor scripts
* [x] update the resulting recipes.json file

Might also be related to https://github.com/andrewrk/mineflayer/issues/222

It might also be a good idea to define a jsonformat for this ( see #2 ) if it's not too complicated.

**Comment by Gjum** [comment]
> check it isn't too ugly

Any ideas how to do this?

**Comment by rom1504** [comment]
I think trying to apply the new format to several recipes in recipes.json might give a good idea if the format is good. For example : 
* some recipes that are correctly handled by the old format : see if they stay readable
 * recipes with inShape
 * recipes with ingredients
 * recipes with outShape
* some recipes that are not handled by the old format

**Comment by Gjum** [comment]
hm, I tried to do that with the example at the bottom.  
Updated it with a 1x1 and 1x2 shape.

Also writing the spock implementation now, nearly done.

**Comment by rom1504** [comment]
Oh yeah right. Looks good.
I'm not sure about one thing though : 
is 
```js
{ // Polished Granite
            "result": {"id": 1, "meta": 2, "amount": 4},
            "inShape": [
                [[1,1], [1,1]],
                [[1,1], [1,1]]
            ]
        },
```
better or : 
```js
{ // Polished Granite
            "result": {"id": 1, "meta": 2, "amount": 4},
            "inShape": [
                [{"id":1, "meta":1}, {"id":1, "meta":1}],
                [{"id":1, "meta":1}, {"id":1, "meta":1}],
            ]
        },
```

the array is a bit confusing I think (since we also have array of ids in that file)

**Comment by roblabla** [comment]
I prefer the first one, personally.

**Comment by Gjum** [comment]
First one is shorter and more human-friendly, although support for both is trivial.

**Comment by rom1504** [comment]
Ok let's keep the first one then.

**Comment by Kupferhirn** [comment]
what about repairing a tools?
http://minecraft.gamepedia.com/Repair

**Comment by Gjum** [comment]
Not sure if that should be included, as an entry per tool and damage value would be the only way with the current format.
I think handling this one level higher would be better, as this can be easily expressed in code, but not in data.

**Comment by rom1504** [comment]
Yeah I don't think this is a recipe. It's not crafting either. 

The "recipe" is even simple to figure out ("Two items of the same type and material can be placed anywhere on the crafting grid, and the result is a single repaired item").

Maybe the data in the tables in that Repair page would be useful for the implementation but that would be in a different .json.

**Comment by Gjum** [comment]
Python utils for Spock: [Done!](https://gist.github.com/Gjum/9c0491aad1c8ec8d6f38#file-recipe-py)
Feel free to modify for mineflayer.

**Comment by Gjum** [comment]
I'm thinking about building a converter from old to new format, just for testing, as long as the wiki scripts are not ready.

**Comment by Gjum** [comment]
Converter done! See #4

**Comment by rom1504** [comment]
Ok, I've done a schema for the old recipes format, I'm going to do one for the new schema too I think.

**Comment by rom1504** [comment]
The schema for the new recipe format is done, see http://prismarinejs.github.io/minecraft-data/

**Comment by rom1504** [comment]
I added a link to the README to the wiki page of the new recipe format.

I wonder if that page should stay in the wiki or be added as a .md file in the doc/ folder ?

**Comment by Gjum** [comment]
For documents that won't change often, .md in doc/ is better than wiki IMO. I only use the wiki when drafting.

**Comment by roblabla** [comment]
:+1: for doc/*.md. Wiki is cool for quick collaboration, but it quickly becomes hard to navigate;

**Comment by rom1504** [comment]
Ok I'll put it there, once I checked everything is ok with the format by doing the last two points (implementing in mineflayer and updating my wiki extractors scripts)

**Comment by rom1504** [comment]
Implemented in mineflayer. Now the only thing remaining here is updating the wiki scripts.

**Comment by rom1504** [comment]
Ok, problem : 
we don't have the "Smooth Granite" --> [1,1] data anywhere, I can't update the recipe without that info.

I think we're going to need to scrape the wiki in the end

**Comment by Gjum** [comment]
Is it really called *Smooth* Granite and not *Polished*?

**Comment by rom1504** [comment]
Yeah I think it's Polished Granite, my confusion came from there https://github.com/PrismarineJS/minecraft-data/wiki/Proposed-new-recipe-format#metadata-in-the-shapes

**Comment by rom1504** [comment]
So, the last step of that issue depends on #7 and then on #8 . it won't be closed very soon.

**Comment by Gjum** [comment]
We are using the new recipe format now, and the remaining problems are all covered with issues. So this can actually be closed.

**Comment by rom1504** [comment]
Yeah you're right.
