### ISSUE TITLE
Changes in Particle IDs need to be tracked, breaks packet_world_particle

### ISSUE THREAD

**Issue by nickelpro** [PrismarineJS/minecraft-data#316]
[Particle IDs](https://wiki.vg/Protocol#Particle) change between MC versions, and minecraft-data should have a way to track that.

Besides semantic differences between particle IDs, the protocol is broken for several versions right now due to particle data using [hard coded values](https://github.com/PrismarineJS/minecraft-data/blob/master/data/pc/1.16.1/protocol.json#L91-L143) that have changed due to the addition of new particle IDs (in this case, Dripping Lava, Landing Lava, and Falling Water).

My recommendation is to create a particles.json to track the particle ids and reference these in the particleData type or something similar.

**Comment by rom1504** [comment]
interesting, thanks for noticing this
I'm curious how you find these problems with the protocol definition.
Any particular method or you just compare manually?

**Comment by nickelpro** [comment]
I'm writing a C++ protocol generator based on minecraft-data. Every time I implement a new type I verify it with a minimal server I've implemented. I first verify that the client doesn't crash, then I verify that the behavior is expected. It's not a fully automatic process, but with some packet captures from a Notchian server it could be.

**Comment by nickelpro** [comment]
Related to the bug, I'm writing a Burger topping to extract the values for all minecraft-data supported versions. That will provide the particles.json we need, then we just need to decide how best to incorporate that into protocol.json

**Comment by nickelpro** [comment]
@rom1504 I have the particle ids for all versions except 1.7.10 (because the "identify" topping doesn't work pre-1.8), would it be more useful to format them as an array? Or as an object that maps the strings to the integer id?

And then the real question is what do you think the best way to incorporate them into the protocol is? Now that I have the ids I can just automate the leg work of correcting the protocol with hard coded integers, which is probably the most compatible option.

**Comment by rom1504** [comment]
How many different kind of particle data is there ?
But yes, it makes sense to try and put all the different kind of particle data in the protocol.
If you have things like id and names it could also be useful as a separate particles.json file.
