### ISSUE TITLE
TypeError: Cannot read property 'entity' of null

### ISSUE THREAD

**Issue by 0vertime-dev** [PrismarineJS/minecraft-data#317]
/Users/overtime/Desktop/WalterBotMC2.0/node_modules/minecraft-protocol/src/transforms/framing.js:67
          } else { throw e }
                   ^

TypeError: Cannot read property 'entity' of null

**Comment by nickelpro** [comment]
Wrong repo, this is a [node-minecraft-protocol](https://github.com/PrismarineJS/node-minecraft-protocol) bug, not a problem with minecraft-data

**Comment by wvffle** [comment]
Closing in favor of #1193
