### ISSUE TITLE
Update to use PDS instead of old json format for ProtoDef? 

### ISSUE THREAD

**Issue by wgaylord** [PrismarineJS/minecraft-data#318]
Is there a way to update / convert the packet defs to use PDS instead of the older Json format that ProtoDefC doesn't support. (Its converter can't convert the protocol defs without requiring fixing of the PDS file.)

Or is it still using the old Json format because node-protdef has not yet been updated to use the new format?

Asking because I was trying to use ProtoDefC to compile to python for working on an MC server and I ran into alot of trouble.

**Comment by rom1504** [comment]
The current format is the json one.
We have node a to js compiler for it too inside node protodef.
@nickelpro is currently working on making a json protocol to c compiler
I advise you go that way
The pds format was an experiment that didn't quite pan out. The json format
advantage is of being simpler and doesn't require anything special to parse.

**Comment by rom1504** [comment]
I will clarify that in the readme

**Comment by wgaylord** [comment]
Okay. Guess its time to try and figure out a way to implement a python read for ProtoDef's format. (Couldn't figure it out back in 2017 and there is still limited information on the format but I guess its time to try again.)

**Comment by Karang** [comment]
@wgaylord 
you have the documentation in the protodef repo: https://github.com/ProtoDef-io/ProtoDef/blob/master/doc/datatypes.md
you can also have a look at the js compiler implementation: https://github.com/ProtoDef-io/node-protodef/blob/master/src/compiler.js
