### ISSUE TITLE
Missing several things from newer versions

### ISSUE THREAD

**Issue by Bottinator22** [PrismarineJS/minecraft-data#338]
From my testing on 1.13.2, it didn't detect 1.13 mobs as hostile.
From my testing on 1.16.1, it didn't detect 1.16 mobs as hostile, but it detected older monsters from 1.14 as hostile.
mineflayer-pathfinder seems to refuse to use netherite tools, likely due to this not having enough data for them.
It appears that for every version, minecraft-data only has the complete data from the previous version.
While it does know of their existence, it doesn't have much data for them.
I believe this is caused by minecraft-data and not prismarine-entity, mineflayer-pathfinder, etc. due to the fact that it works on the version after the current one, and the fact that mineflayer-pathfinder doesn't directly mention any IDs in its "find best tool" func.

**Comment by rom1504** [comment]
would be good to open precise issues in the relevant packages. this is too vague to act upon
