### ISSUE TITLE
Maximum string length

### ISSUE THREAD

**Issue by vagola** [PrismarineJS/minecraft-data#360]
The protocol has a bunch of fixed length limited strings. Currently, these data are not available. 

https://wiki.vg/index.php?title=Protocol&oldid=15346#Encryption_Request

**Comment by Karang** [comment]
In the protocol, these "fixed-size" strings are always prefixed by their size, as stated in https://wiki.vg/index.php?title=Protocol&oldid=15346#Data_types
So we don't need to actually store this information. For what use case do you need it ?

**Comment by vagola** [comment]
Sanity check that packet are not corrupted.

**Comment by rom1504** [comment]
Corrupted in what sense ?

**Comment by vagola** [comment]
It's looks like this relates more to protodef specification. `countType` is limited to data type maximum length. By default Minecraft string can't be longer then 2^16. This allows victim to attack server with long strings

**Comment by extremeheat** [comment]
Strings shouldn’t exhaust resources, it’s just a matter of copying some bytes from the buffer to a new data type. In JS, there is some small overhead converting, in C++ there is none. If you’re writing a parser/generator, just throw an exception if a string or other data type has a length past the end of the buffer. 

If you’re parsing the string as JSON or something yes it does bring up memory/recursion issues, so you can add in your own bounds checks outside the protocol. Note that neither protocol buffers or flatbuffers implement size limits beyond the data type. 

Now if you just want to be correct with the vanilla implementation, I guess it could be helpful to have this data for sanity checks, but i don’t know if it’s worthwhile, it’s more like a minor implementation detail

**Comment by vagola** [comment]
Well, i agree that this is a very minor feature. After i wrote protodef parser not a big fan to change specification :)
