### ISSUE TITLE
define the schema of a future Windows.json

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/minecraft-data#37]
* https://github.com/andrewrk/mineflayer/blob/master/lib/windows.js#L22
* https://github.com/SpockBotMC/SpockBot/blob/master/spock/plugins/helpers/inventory.py#L204

22:09 <+Gjum> it's just the window name (for protocol), readable name (although that can get set by server), named slot ranges, names for the properties, and later buttons
22:10 <+Gjum> properties are for example the smelting progress of a furnace
22:11 <+Gjum> buttons would just be list[id -> "name"]
22:12 <+Gjum> and then there are some edge cases like the horse, and the player itself
22:12 <+Gjum> horse has an entity id, player has armor and crafting, but no nameID

**Comment by Gjum** [comment]
`inventorySlotStart`, which is needed by mineflayer, should be dynamic for some windows like chests. Especially since the server sends it.

I am not sure, but I think I saw some sort of generic window on a Bukkit server, that can have any amount of slots.

**Comment by Gjum** [comment]
I made an example JSON, and am now creating a schema from it:
```json
[
  {
    "id": "minecraft:beacon",
    "name": "Beacon",
    "slots": [
      {
        "name": "input",
        "slot": 0
      }
    ],
    "properties": [
      "level",
      "effect one",
      "effect two"
    ],
    "buttons": [
      // TODO
    ]
  }
  {
    "id": "minecraft:brewing_stand",
    "name": "Brewing Stand",
    "slots": [
      {
        "name": "ingredient",
        "slot": 0
      },
      {
        "name": "result",
        "from": 1,
        "to": 3
      }
    ],
    "properties": [
      "brew time"
    ]
  }
]
```

**Comment by Gjum** [comment]
Example got updated, schema is done. Creating PR now.
