### ISSUE TITLE
Where is the version 1.16.5?

### ISSUE THREAD

**Issue by Bapobe** [PrismarineJS/minecraft-data#394]
Sorry to bother you guys I just really need this for my server.

**Comment by nickelpro** [comment]
You can find a given version's data by looking in dataPath.json
https://github.com/PrismarineJS/minecraft-data/blob/master/data/dataPaths.json#L898-L920

**Comment by Bapobe** [comment]
> You can find a given version's data by looking in dataPath.json
> https://github.com/PrismarineJS/minecraft-data/blob/master/data/dataPaths.json#L898-L920
> 
> Each entry for that version points to where you can find the associated data. So for example block data for 1.6.5 is going to be found in [pc/1.16.2/blocks.json](https://github.com/PrismarineJS/minecraft-data/blob/master/data/pc/1.16.2/blocks.json).

Sorry, you misunderstood I meant where is support for V1.16.5 is there going to be because it does not work with 1.16.5 and you do not list 1.16.5 as a supported version only going up to 1.16.5 is there a way to get it to work with 1.16.5 or can you update it to get it to work with the newer version.

**Comment by u9g** [comment]
> > You can find a given version's data by looking in dataPath.json
> > https://github.com/PrismarineJS/minecraft-data/blob/master/data/dataPaths.json#L898-L920
> > Each entry for that version points to where you can find the associated data. So for example block data for 1.6.5 is going to be found in [pc/1.16.2/blocks.json](https://github.com/PrismarineJS/minecraft-data/blob/master/data/pc/1.16.2/blocks.json).
> 
> Sorry, you misunderstood I meant where is support for V1.16.5 is there going to be because it does not work with 1.16.5 and you do not list 1.16.5 as a supported version only going up to 1.16.5 is there a way to get it to work with 1.16.5 or can you update it to get it to work with the newer version.

update what? this is a language agnostic data repo, theres no src code here. 1.16.5 data is fine here and works in mineflayer

**Comment by Bapobe** [comment]
> > > You can find a given version's data by looking in dataPath.json
> > > https://github.com/PrismarineJS/minecraft-data/blob/master/data/dataPaths.json#L898-L920
> > > Each entry for that version points to where you can find the associated data. So for example block data for 1.6.5 is going to be found in [pc/1.16.2/blocks.json](https://github.com/PrismarineJS/minecraft-data/blob/master/data/pc/1.16.2/blocks.json).
> > 
> > 
> > Sorry, you misunderstood I meant where is support for V1.16.5 is there going to be because it does not work with 1.16.5 and you do not list 1.16.5 as a supported version only going up to 1.16.5 is there a way to get it to work with 1.16.5 or can you update it to get it to work with the newer version.
> 
> update what? this is a language agnostic data repo, theres no src code here. 1.16.5 data is fine here and works in mineflayer

https://imgur.com/a/rEMVolw This what I mean.
