### ISSUE TITLE
How are these files generated?

### ISSUE THREAD

**Issue by u9g** [PrismarineJS/minecraft-data#399]
Looking for help finding sources for any data with a ?:

* biomes - [burger][1] + [burger-extractor][2] (not working >1.16 in my testing)
* commands - ?
* instruments - manual
* items - [burger][1] + [burger-extractor][2] + [turbo-invention][4]
* materials - manual
* blocks - [burger][1] + [burger-extractor][2]
* blockCollisionShapes - [McDataExtracting][3]
* recipes - [burger][1] + [burger-extractor][2]
* windows - manual
* entities - [burger][1] + [burger-extractor][2]
* protocol - manual
* version - manual
* effects - manual
* enchantments - manual
* language - [minecraft-jar-extractor][5]
* foods - gone?
* particles - manual
* blockLoot - [minecraft-jar-extractor][5]
* entityLoot - [minecraft-jar-extractor][5]
* mapIcons - manual

[1]: https://github.com/Pokechu22/Burger
[2]: https://github.com/PrismarineJS/burger-extractor
[3]: https://github.com/PrismarineJS/McDataExtracting
[4]: https://github.com/u9g/turbo-invention
[5]: https://github.com/PrismarineJS/minecraft-jar-extractor

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/minecraft-data#extraction

https://github.com/PrismarineJS/minecraft-data/blob/master/doc/add-data-new-version.md

**Comment by u9g** [comment]
> https://github.com/PrismarineJS/minecraft-data#extraction
> 
> https://github.com/PrismarineJS/minecraft-data/blob/master/doc/add-data-new-version.md

Thank you for this, but how is https://github.com/PrismarineJS/minecraft-data/blob/master/doc/add-data-new-version.md#map-icons helpful? it tells you how to get a png, which you get a json from how?

**Comment by rom1504** [comment]
fixed by u9g
