### ISSUE TITLE
Add particle data.

### ISSUE THREAD

**Issue by Zn10plays** [PrismarineJS/minecraft-data#405]
Add particle data to McData. For example name, states, and other info

**Comment by nickelpro** [comment]
Particle names and IDs are already a part of [particles.json](https://github.com/PrismarineJS/minecraft-data/blob/master/schemas/particles_schema.json). This information could be potentially expanded, what's there now is just what's useful for the protocol. The relevant burger topping is [particletypes.py](https://github.com/mcdevs/Burger/blob/master/burger/toppings/particletypes.py) if someone wanted to automate it. Although it's worth mentioning that IIRC the particle types classes actually have much more information in them than name and ID.

**Comment by u9g** [comment]
> Particle names and IDs are already a part of [particles.json](https://github.com/PrismarineJS/minecraft-data/blob/master/schemas/particles_schema.json). This information could be potentially expanded, what's there now is just what's useful for the protocol. The relevant burger topping is [particletypes.py](https://github.com/mcdevs/Burger/blob/master/burger/toppings/particletypes.py) if someone wanted to automate it. Although it's worth mentioning that IIRC the particle types classes actually have much more information in them than name and ID.

Unless I’m missing something, the topping seems to not work for 1.16.5

**Comment by nickelpro** [comment]
Haven't tested it at all, I'll take a look at it now. Likely a class moved, shouldn't be a rough fix

**Comment by nickelpro** [comment]
Nope, works fine for me

```
$ python munch.py --download=1.16.5 --toppings=particletypes
[
    {
        "classes": {
            "anvilchunkloader": "zs",
            "biome.list": "kp",
            "biome.register": "kp",
            "block.list": "bup",
            "block.register": "bup",
            "blockstate": "ceh",
            "blockstatecontainer": "cei$a",
            "chatcomponent": "nr",
            "entity.list": "aqe",
            "enumfacing.plane": "gc$c",
            "identifier": "vk",
            "item.list": "bmd",
            "item.register": "bmd",
            "itemstack": "bmb",
            "metadata": "uv",
            "nbtcompound": "md",
            "nethandler.client": "dwu",
            "nethandler.server": "aaz",
            "packet.connectionstate": "ne",
            "packet.packetbuffer": "nf",
            "particle": "hf",
            "particletypes": "hh",
            "recipe.superclass": "jg",
            "sounds.event": "adq",
            "sounds.list": "adq",
            "tileentity.superclass": "ccj"
        },
        "particletypes": [
            "ambient_entity_effect",
            "angry_villager",
            "barrier",
            "block",
            "bubble",
            "cloud",
            "crit",
            "damage_indicator",
            "dragon_breath",
            "dripping_lava",
            "falling_lava",
            "landing_lava",
            "dripping_water",
            "falling_water",
            "dust",
            "effect",
            "elder_guardian",
            "enchanted_hit",
            "enchant",
            "end_rod",
            "entity_effect",
            "explosion_emitter",
            "explosion",
            "falling_dust",
            "firework",
            "fishing",
            "flame",
            "soul_fire_flame",
            "soul",
            "flash",
            "happy_villager",
            "composter",
            "heart",
            "instant_effect",
            "item",
            "item_slime",
            "item_snowball",
            "large_smoke",
            "lava",
            "mycelium",
            "note",
            "poof",
            "portal",
            "rain",
            "smoke",
            "sneeze",
            "spit",
            "squid_ink",
            "sweep_attack",
            "totem_of_undying",
            "underwater",
            "splash",
            "witch",
            "bubble_pop",
            "current_down",
            "bubble_column_up",
            "nautilus",
            "dolphin",
            "campfire_cosy_smoke",
            "campfire_signal_smoke",
            "dripping_honey",
            "falling_honey",
            "landing_honey",
            "falling_nectar",
            "ash",
            "crimson_spore",
            "warped_spore",
            "dripping_obsidian_tear",
            "falling_obsidian_tear",
            "landing_obsidian_tear",
            "reverse_portal",
            "white_ash"
        ],
        "source": {
            "classes": 5445,
            "file": "1.16.5.jar",
            "other": 14646,
            "size": 17547153
        }
    }
]
```

**Comment by u9g** [comment]
in

> Nope, works fine for me
> 
> ```
> $ python munch.py --download=1.16.5 --toppings=particletypes
> [
>     {
>         "classes": {
>             "anvilchunkloader": "zs",
>             "biome.list": "kp",
>             "biome.register": "kp",
>             "block.list": "bup",
>             "block.register": "bup",
>             "blockstate": "ceh",
>             "blockstatecontainer": "cei$a",
>             "chatcomponent": "nr",
>             "entity.list": "aqe",
>             "enumfacing.plane": "gc$c",
>             "identifier": "vk",
>             "item.list": "bmd",
>             "item.register": "bmd",
>             "itemstack": "bmb",
>             "metadata": "uv",
>             "nbtcompound": "md",
>             "nethandler.client": "dwu",
>             "nethandler.server": "aaz",
>             "packet.connectionstate": "ne",
>             "packet.packetbuffer": "nf",
>             "particle": "hf",
>             "particletypes": "hh",
>             "recipe.superclass": "jg",
>             "sounds.event": "adq",
>             "sounds.list": "adq",
>             "tileentity.superclass": "ccj"
>         },
>         "particletypes": [
>             "ambient_entity_effect",
>             "angry_villager",
>             "barrier",
>             "block",
>             "bubble",
>             "cloud",
>             "crit",
>             "damage_indicator",
>             "dragon_breath",
>             "dripping_lava",
>             "falling_lava",
>             "landing_lava",
>             "dripping_water",
>             "falling_water",
>             "dust",
>             "effect",
>             "elder_guardian",
>             "enchanted_hit",
>             "enchant",
>             "end_rod",
>             "entity_effect",
>             "explosion_emitter",
>             "explosion",
>             "falling_dust",
>             "firework",
>             "fishing",
>             "flame",
>             "soul_fire_flame",
>             "soul",
>             "flash",
>             "happy_villager",
>             "composter",
>             "heart",
>             "instant_effect",
>             "item",
>             "item_slime",
>             "item_snowball",
>             "large_smoke",
>             "lava",
>             "mycelium",
>             "note",
>             "poof",
>             "portal",
>             "rain",
>             "smoke",
>             "sneeze",
>             "spit",
>             "squid_ink",
>             "sweep_attack",
>             "totem_of_undying",
>             "underwater",
>             "splash",
>             "witch",
>             "bubble_pop",
>             "current_down",
>             "bubble_column_up",
>             "nautilus",
>             "dolphin",
>             "campfire_cosy_smoke",
>             "campfire_signal_smoke",
>             "dripping_honey",
>             "falling_honey",
>             "landing_honey",
>             "falling_nectar",
>             "ash",
>             "crimson_spore",
>             "warped_spore",
>             "dripping_obsidian_tear",
>             "falling_obsidian_tear",
>             "landing_obsidian_tear",
>             "reverse_portal",
>             "white_ash"
>         ],
>         "source": {
>             "classes": 5445,
>             "file": "1.16.5.jar",
>             "other": 14646,
>             "size": 17547153
>         }
>     }
> ]
> ```

nvm, i meant that we dont have a module for burgerextractor for particles to make the particles.json iirc

**Comment by nickelpro** [comment]
Ya that's because I have no idea how to write javascript. It's a dead simple transformation though, the index of the name in the `particletypes` list is the particle ID. Someone who knows JS could write an extractor in a second.

**Comment by u9g** [comment]
> Ya that's because I have no idea how to write javascript. It's a dead simple transformation though, the index of the name in the `particletypes` list is the particle ID. Someone who knows JS could write an extractor in a second.

ah you were right, made https://github.com/PrismarineJS/burger-extractor/pull/15

**Comment by nickelpro** [comment]
Fairly certain this can be closed unless I'm missing something

**Comment by nickelpro** [comment]
Closing this for now. I'm unaware of any particle data that isn't covered between particles.json and protocol.json. If there's something that we're missing it can be worked on in a bug report that lays out specifically what's needed
