### ISSUE TITLE
Add minStateId, maxStateId and defaultState to legacy versions of blocks.json

### ISSUE THREAD

**Issue by IceTank** [PrismarineJS/minecraft-data#428]
Block instance for versions <1.13 do not contain minStateId, maxStateId and defaultState. The states are needed in cross version compatibility.

**Comment by rom1504** [comment]
not convinced, there is no state in <1.13
shouldn't this be handled in prismarine-block ?

**Comment by nickelpro** [comment]
Blocks don't have states pre-flattening, they have variations. MCD is not the place to hide the complexity of the pre/post flattening switch, just like we don't attempt to hide pre/post netty, or large differences in packet structure.
