### ISSUE TITLE
Protocol packet field type mismatch

### ISSUE THREAD

**Issue by Gnog3** [PrismarineJS/minecraft-data#453]
Packet: NBT Query Response, in protocol since 1.13.
wiki.vg says "NBT" field can be TAG_END (0) which is "optionalNbt" type in protocol.json (and it is logical that it is optional) but in protocol.json it has nbt type.
```
"packet_nbt_query_response": [
          "container",
          [
            {
              "name": "transactionId",
              "type": "varint"
            },
            {
              "name": "nbt",
              "type": "nbt"
            }
          ]
        ],
```
![image](https://user-images.githubusercontent.com/52673876/129457629-41626706-2149-41be-9794-7203e8dcad3f.png)

**Comment by rom1504** [comment]
welcome a pr
