### ISSUE TITLE
mcpc 1.18

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/minecraft-data#474]

**Comment by natebot13** [comment]
I have a datapack generator that uses the biome information of MC Java edition. Would love to have the updated Minecraft 1.18 biome data.

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/minecraft-data/blob/master/doc/add-data-new-version.md has the latest information on how to best generate the new data 
See https://github.com/PrismarineJS/minecraft-data-auto-updater in particular

**Comment by rom1504** [comment]
missing materials and a few others

more info there https://github.com/PrismarineJS/mineflayer/pull/2339#issuecomment-1008188656

**Comment by rom1504** [comment]
mostly done
