### ISSUE TITLE
1.18

### ISSUE THREAD

**Issue by pozhiloy-enotik** [PrismarineJS/minecraft-data#476]

**Comment by rom1504** [comment]
Duplicate of #474

**Comment by SylveonBottle** [comment]
Is this request for 1.18 bedrock, or java addition? 
Or does #474 also handle java edition as well?

I was going to make a suggestion for 1.18 java edition, but it appears that this was reported as duplicate.. of bedrock edition?

**Comment by rom1504** [comment]
#474 is for mcpc
Bedrock 1.18 is already done

**Comment by SylveonBottle** [comment]
So which issue is for java 1.18?

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/minecraft-data/issues/474
mcpc = java
