### ISSUE TITLE
Generate doc from json schemas ?

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/minecraft-data#5]
https://github.com/lbovet/docson
see an example here http://lbovet.github.io/docson/index.html#/docson/examples/example.json

But I'm not sure where this would go. And maybe the json file is readable enough ?

**Comment by Gjum** [comment]
These visualizations are good for large JSON structures, but the structures in this project are small enough to be comprehensible (largest are in [blocks.json](../blob/master/enums/blocks.json)).

**Comment by rom1504** [comment]
It might be useful for the recipes schema though ( [recipes_schema.json](https://github.com/PrismarineJS/minecraft-data/blob/master/enums_schemas/recipes_schema.json) )

The idea is that it would be a automatically generated version of https://github.com/PrismarineJS/minecraft-data/wiki/Recipe-format

**Comment by rom1504** [comment]
It would look like that http://rom1504.fr/docson/index.html?json=items .

**Comment by rom1504** [comment]
or like that http://rom1504.fr/docson/list.html

**Comment by rom1504** [comment]
done http://prismarinejs.github.io/minecraft-data/
It adds only two small files in the gh-pages branch : 
* a 43 lines index.html
* a 3 lines .gitmodules

Nothing changed on master.

**Comment by rom1504** [comment]
The only reason when it will be need to change things in the gh-pages branch is if we want to change the index.html.
The index.html automatically take the last json schema from master (without needing to change anything on the gh-pages branch)
