### ISSUE TITLE
Improve the docgen of protocol values

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/minecraft-data#50]
http://prismarinejs.github.io/minecraft-data/#protocolTableA is useful but it would be even more useful if it displayed stuff in tables like wiki.vg

inspiration from the transformation in https://gist.github.com/rom1504/0d41cc284de99dfc8b6e

**Comment by roblabla** [comment]
http://roblabla.github.io/minecraft-data/

**Comment by rom1504** [comment]
Open a PR when you're done ;) 
There might be a few things to adjust relative to the changes I made in #53

**Comment by rom1504** [comment]
* [ ] buffer count type
* [ ] improving container and switch ?
* [ ] comments #56 : markdown ?

**Comment by rom1504** [comment]
See #59 and #60

**Comment by rom1504** [comment]
and #68

**Comment by roblabla** [comment]
Closed in favor of #60 and #167
