### ISSUE TITLE
Deepslate variant translation strings are not listed in the 1.18 language.json

### ISSUE THREAD

**Issue by JoakimThorsen** [PrismarineJS/minecraft-data#547]
They are however listed in the 1.17 language.json, which is a bit odd
1.18: https://github.com/PrismarineJS/minecraft-data/blob/master/data/pc/1.18/language.json
1.17: https://github.com/PrismarineJS/minecraft-data/blob/master/data/pc/1.17/language.json

Edit: in fact, it seems like every (at least block-) addition from 1.17 is missing from the 1.18 language file

**Comment by u9g** [comment]
can you see if they are listed in the pr for more 1.18 data?
