### ISSUE TITLE
Don't use relative paths in tools

### ISSUE THREAD

**Issue by roblabla** [PrismarineJS/minecraft-data#55]
Some tools use relative paths (e.g. https://github.com/PrismarineJS/minecraft-data/blob/1.8/tools/js/wiki_extractor/protocol_extractor.js#L53), which leads to them not working properly when used from another directory. They should instead use `__dirname` to behave properly at all times.

**Comment by rom1504** [comment]
Yeah agreed.

**Comment by rom1504** [comment]
Fixed. (see https://github.com/PrismarineJS/mcdevs-wiki-extractor/blob/master/bin/protocol_to_json.js)
