### ISSUE TITLE
1.18.30+ has outdated blockStates

### ISSUE THREAD

**Issue by lowlines** [PrismarineJS/minecraft-data#561]
It looks like 1.18.30+ has new data as stuff like blockStates doesn't match up with what is in the world. For instance bedrock blocks now have an index of 6971.

**Comment by lowlines** [comment]
Doing some tests against 1.19.10.20 (bedrock dedicated server as the latest preview build throws errors), the bedrock block id is now 7017. The key takeaway is that since 1.18.30, the runtime order doesn't match the alphabetical order of block names, like in previous builds.

**Comment by extremeheat** [comment]
There is currently only protocol data for bedrock 1.18.30

**Comment by extremeheat** [comment]
See doc https://github.com/PrismarineJS/minecraft-data/blob/master/doc/bedrock.md

**Comment by extremeheat** [comment]
Will update tomorrow
