### ISSUE TITLE
Add version: 1.19

### ISSUE THREAD

**Issue by u9g** [PrismarineJS/minecraft-data#573]
- [x] Version folder containing "version.json" created
- [x] "version.json" filled out appropriately
- [x] Added version to dataPath.json
- [x] "version" field of dataPath.json points to new version folder
- [x] Version added to common/versions.json
- [x] Version added to ReadMe

Additional Requirements For This Update:

**Comment by rom1504** [comment]
This like this is done ?

**Comment by nickelpro** [comment]
Checklist is complete, I would hesitate to close until protocol is merged. Feels premature to declare 1.19 done

**Comment by rob9315** [comment]
fyi there are still issues, which get fixed by #589
