### ISSUE TITLE
The mapping of permission_level may be wrong

### ISSUE THREAD

**Issue by Daiki51** [PrismarineJS/minecraft-data#581]
The permission_level of the newly added request_permissions packet seems to be different from the permission_level of the adventure_settings packet.

request_permissions
 - permission_level
   - visitor (0)
   - member (2)
   - operator (4)

adventure_settings
 - permission_level
   - visitor (0)
   - member (1)
   - operator (2)
   - custom (3)

**Comment by rom1504** [comment]
What data are you referring to?
