### ISSUE TITLE
blocksB2J and blocksJ2B  uses wrong syntax

### ISSUE THREAD

**Issue by Sertonix** [PrismarineJS/minecraft-data#611]
The syntax bedrock uses for block states is not the same as in java edition.
eg.
`minecraft:note_block[instrument=pling,note=24,powered=false]`
should be:
`minecraft:note_block["instrument":"pling","note":24,"powered":false]`

[McWiki](https://minecraft.fandom.com/wiki/Argument_types#BlockStateCommandParam)

**Comment by extremeheat** [comment]
There is no bug here. The minecraft-data schema does not refer to any specific format beyond mapping state between minecraft Java and bedrock editions.

#532 discusses changing this schema again to a flat schema in line with the rest of minecraft-data

**Comment by Sertonix** [comment]
ok, I will take a look at that
