### ISSUE TITLE
bedrock packet_inventory_transaction block_position y level incorrectly deserialized

### ISSUE THREAD

**Issue by Bluebotlabz** [PrismarineJS/minecraft-data#645]
When I interract with a block at:
~~~json
{
    "x": 8,
    "y": -22,
    "z": 5
}
~~~

I get the following inventory transaction packet:
~~~json
{
    "transaction": {
        "legacy": {
            "legacy_request_id": 0
        },
        "transaction_type": "item_use",
        "actions": [],
        "transaction_data": {
            "action_type": "click_block",
            "block_position": {
                "x": 8,
                "y": 2147483637,
                "z": 5
            },
            "face": 10,
            "hotbar_slot": 0,
            "held_item": {
                "network_id": 0
            },
            "player_pos": {
                "x": 9.751617431640625,
                "y": -21.317489624023438,
                "z": 5.578364372253418
            },
            "click_pos": {
                "x": 0.75,
                "y": 0.27826499938964844,
                "z": 0.4701395034790039
            },
            "block_runtime_id": 6562
        }
    }
}
~~~

Notice how the `block_position` attribute of the `transaction_data` is incorrect:
~~~json
"block_position": {
    "x": 8,
    "y": 2147483637,
    "z": 5
},
~~~

Here is a table of expected values:
| expected y-coordinate | packet y-coordinate |
|-----------------------|---------------------|
| -22                   | 2147483637          |
| -23                   | -2147483637         |
| -24                   | 2147483636          |
| -25                   | -2147483636         |
| -26                   | 2147483635          |
| -13                   | -2147483642         |

**Comment by irkmandeer** [comment]
This has been resolved with https://github.com/PrismarineJS/minecraft-data/pull/730
