### ISSUE TITLE
MCPE support

### ISSUE THREAD

**Issue by roblabla** [PrismarineJS/minecraft-data#65]
It'd be interesting to have the MCPE data available here as well. I believe the two games are close enough to actually be able to support both schema types. The protocol will probably be the one file to change the most, but I believe its schema won't have to change all that much either

**Comment by rom1504** [comment]
Yeah I agree , I guess we would follow the same organization than versions (so branches for now and possibly folders if we do choose to use folders in #64 )

**Comment by rom1504** [comment]
It would be nice to find some good sources to build a protocol.json for mcpe.

**Comment by roblabla** [comment]
@rom1504 there's also PocketBurger https://github.com/PocketMine/PocketBurger

**Comment by rom1504** [comment]
Also see where @Creeplays is taking his data from (https://github.com/mhsjlw/mcpe-server/blob/master/lib/net/protocol.js#L75)

**Comment by rom1504** [comment]
http://minecraft.gamepedia.com/Pocket_Edition : ah the last version is only available in windows 10

**Comment by mhsjlw** [comment]
@rom1504 Don't use the original source for the mcpe-server, we've updated the packet names so the old Protocol.js file is no longer usable

**Comment by rom1504** [comment]
What about https://github.com/PocketMine/PocketMine-MP/tree/master/src/pocketmine/network/protocol ? seems more or less up to date

**Comment by mhsjlw** [comment]
@rom1504 Looked at it a while ago, it is useless

**Comment by mhsjlw** [comment]
This... now this... is what is useful https://github.com/PocketMine/PocketMine-MP/blob/master/src/pocketmine/network/protocol/Info.php

**Comment by rom1504** [comment]
No, that second file give the packets id<-->name, but that's not very useful, the first link give you all the fields for each packet.

**Comment by mhsjlw** [comment]
@rom1504 Can we turn this into documentation?

**Comment by rom1504** [comment]
We can probably turn it into a protocol.json, which can then be converted automatically to a doc.
It's the 0.12 branch we'd be more interested about https://github.com/PocketMine/PocketMine-MP/tree/mcpe-0.12/src/pocketmine/network/protocol

**Comment by rom1504** [comment]
https://github.com/rom1504/mcpe-protocol-extractor

**Comment by rom1504** [comment]
I guess we'll be following the same structure as currently : a new branch for each mcpe version.

So that means a mcpe-0.12 branch.

It's related to #64 . Continuing this comment there.

**Comment by phase** [comment]
What if this was put in another repository, like *mcpe-data*?

**Comment by roblabla** [comment]
It'd be best to keep in same repo so it works flawlessly in nmp. The two games should be close enough for the schemas not to diverge I think. What advantage would there be to a different repo?

**Comment by mhsjlw** [comment]
@roblabla I am one for keeping it in this repo. For example, if I need minecraft-data for both the games instead of grabbing 2 repositories I can just have one with all the info I need. Additionally, MCPE protocol and data is quite small at the moment but is getting bigger so it shouldn't be too bad if we keep it around

**Comment by rom1504** [comment]
yeah, this is minecraft-data not mcpc-data. It probably makes sense to have all the data inside this repo. It doesn't take much room anyway ;)

**Comment by rom1504** [comment]
some more data from @mhsjlw 
https://gist.github.com/mhsjlw/447233933f3a68a10cea

**Comment by rom1504** [comment]
some recent work https://github.com/mhsjlw/pocket-minecraft-protocol

**Comment by mhsjlw** [comment]
to be exact, https://github.com/mhsjlw/pocket-minecraft-protocol/blob/master/data/protocol.json it is currently up-to-date with MCPE 0.14

**Comment by rom1504** [comment]
okay the protocol.json is actually getting almost ready.
It will soon be time to think about moving it to mcdata.
That requires some organization thinking.

Should there be a data/pe-0.14 ? should the pc version be prefixed by pc- ?
Or should we have a data/pe/ and data/pc/ ?

Also, is it a good idea to put everything in that repo or should we not split it in a minecraft-data-pe repo ? (still keeping the same schema by putting the schema somewhere else for example)

**Comment by rom1504** [comment]
I think the data/pe/ and data/pc/ is probably the more simple option.

Any thoughts @deathcap @roblabla @mhsjlw ?

**Comment by deathcap** [comment]
@rom1504 data/pe/ and data/pc/ seems reasonable to me. Or data/pe-0.14, but having MCPE and MCPC in separate directories would keep the namespace cleaner.

**Comment by mhsjlw** [comment]
Ok, well, it's pretty official, we've started development of [numerous-alpaca](https://github.com/numerous-alpaca/numerous-alpaca) and [mcpe-chunk](https://github.com/mhsjlw/node-mcpe-chunk) among others. MCPE data will be placed in minecraft-data. We also have 0.30c so this is a very universal minecraft-data. It just should be noted that all this MCPE data is extremely bleeding-edge and it will be updated often, especially with the upcoming encryption update.

**Comment by mhsjlw** [comment]
Also see https://github.com/PrismarineJS/minecraft-data/pull/138

**Comment by rom1504** [comment]
mcpe data is there.
Let's just update the README with that info and then this issue can be closed.

**Comment by rom1504** [comment]
Done. The adding of other pe files can be tracked in other issues.
