### ISSUE TITLE
Add version: 1.19.3

### ISSUE THREAD

**Issue by dolosarafat** [PrismarineJS/minecraft-data#664]
- [ ] Version folder containing "version.json" created
- [ ] "version.json" filled out appropriately
- [ ] Added version to dataPath.json
- [ ] "version" field of dataPath.json points to new version folder
- [ ] Version added to common/versions.json
- [ ] Version added to ReadMe

Additional Requirements For This Update:
Please add ;(

**Comment by frej4189** [comment]
See #661

**Comment by rom1504** [comment]
@frej4189 could you retrieve the updates you did and make
* a data PR (everything but protocol)
* a protocol PR (one commit copying 1.19.2 and another commit making the changes)


if anyone feel like doing it, go ahead

**Comment by extremeheat** [comment]
Done in https://github.com/PrismarineJS/minecraft-data/pull/668 and https://github.com/PrismarineJS/minecraft-data/pull/669
