### ISSUE TITLE
Try other json schema validators for better speed and better errors

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/minecraft-data#69]
https://github.com/ebdrup/json-schema-benchmark#performance

jsonschema errors aren't always useful, and it's fairly slow.

Maybe https://github.com/mafintosh/is-my-json-valid

**Comment by Gjum** [comment]
Keep this in mind: https://github.com/ebdrup/json-schema-benchmark/blob/master/reports/is-my-json-valid.md

**Comment by rom1504** [comment]
so looking at this now https://github.com/ebdrup/json-schema-benchmark

ajv won the race. I'm going to try to use it.

**Comment by rom1504** [comment]
Now using ajv 
* https://circleci.com/gh/PrismarineJS/minecraft-data/388 86s
* https://circleci.com/gh/PrismarineJS/minecraft-data/389 2s

43x speed up. I wish I could say I did that kind of speed up every day !
