### ISSUE TITLE
where's flattening_ids.txt

### ISSUE THREAD

**Issue by ExBitchss** [PrismarineJS/minecraft-data#697]
that project have flattening_ids? im not finding it and if doesnt have can you add it? i need that ids "legacy block aliases"

**Comment by extremeheat** [comment]
Why do you need this data? It's not in the dataPaths currently.

**Comment by extremeheat** [comment]
See the common/legacy.json file exposed in node-minecraft-data's .legacy field, or use prismarine-block if you can.
