### ISSUE TITLE
Particles.json

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/minecraft-data#75]
http://wiki.vg/Protocol#Particle

**Comment by phase** [comment]
Is this just a big table of the numerical ids? Like
```
"particles": {
    "explode": 0,
    "largeexplosion": 1,
    //...
}
```

We could just modify this manually if it isn't documented on the Minecraft wiki anywhere.

**Comment by rom1504** [comment]
It's there http://wiki.vg/Protocol#Particle
And it would be something like that yeah.
Or more like:

```js
[
{"name":"explode","id":0},
{"name":"largeexplosion","id":1},
...
]
```

I haven't had time to do this, but I'll probably just add an extractor for this in https://github.com/PrismarineJS/mcdevs-wiki-extractor so we have that data from wiki.vg

**Comment by nickelpro** [comment]
Some particle types have extended data, that should probably be in there too

**Comment by nickelpro** [comment]
Fixed in https://github.com/PrismarineJS/minecraft-data/pull/319
