### ISSUE TITLE
1.20 - Block States data is in incorrect order

### ISSUE THREAD

**Issue by MathiasElgaard** [PrismarineJS/minecraft-data#757]
In blocks.json, the list of states for various blocks is in incorrect order.

For example, the states for oak_door are listed in the order: `"half", "facing", "open", "hinge", "powered"`

https://github.com/PrismarineJS/minecraft-data/blob/60682082d2dda5d5e7827ae908236dc1fbd8b79d/data/pc/1.20/blocks.json#L5919-L5979

But in Minecraft, the actual order is: `"facing", "half", "hinge", "open", "powered"`

![javaw_4N2FtKKm7L](https://github.com/PrismarineJS/minecraft-data/assets/49698905/eaced151-73ea-4b2b-9c52-9fff7055c4f0)

This is breaking compatibility with e.g. prismarine-block's block.getProperties()

Other blocks that have an incorrect state order include trapdoors, fence gates, buttons, redstone and pistons.

Previous versions don't have the incorrect ordering, I checked versions between 1.16.0 - 1.19.4, and all of the blocks have the correct order.

**Comment by extremeheat** [comment]
cc @u9g, do you know how the extractor for this works? Does it do any sorting or keep the vanilla order? Maybe we could add a test for this.

**Comment by u9g** [comment]
> cc @u9g, do you know how the extractor for this works? Does it do any sorting or keep the vanilla order? Maybe we could add a test for this.

https://github.com/PrismarineJS/minecraft-data-generator-server/blob/83fca6907591ce30458334620bfd5386df6d8f98/src/main/java/dev/u9g/minecraftdatagenerator/generators/BlocksDataGenerator.java#L84

Might be worth looking at this with a debugger or even looking how the minecraft server does it
