### ISSUE TITLE
Update to 1.20.30

### ISSUE THREAD

**Issue by VortexxJS** [PrismarineJS/minecraft-data#773]
Please update to 1.20.30

**Comment by rom1504** [comment]
Out of curiosity how are you using bedrock-protocol ?

**Comment by VortexxJS** [comment]
I make a bot that basically lets you manage your realm from discord or a website.

**Comment by rom1504** [comment]
Is it on GitHub?

**Comment by VortexxJS** [comment]
No, it will be a public to use bot.

**Comment by rom1504** [comment]
So you mean available as a service but not opensource?

**Comment by VortexxJS** [comment]
Yes

**Comment by extremeheat** [comment]
Done with #777
