### ISSUE TITLE
Review and fix protocol.json for 1.20.2

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/minecraft-data#788]
See https://github.com/PrismarineJS/minecraft-data/blob/master/data/pc/1.20.2/protocol.json

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/minecraft-data/pull/786 introduced there

**Comment by rom1504** [comment]
We need a description of what was changed there. Ideally with pointers to some reference.
Ideally with step by step commits introducing one change at a time

**Comment by wgaylord** [comment]
https://gist.github.com/wgaylord/e1196e832bf5e385b00c85c767de0d40

All of this was based on wiki.vg. https://wiki.vg/index.php?title=Pre-release_protocol&oldid=18386 is also a good source as the last diff between 1.20.2 and 1.20.1 on it.

**Comment by extremeheat** [comment]
1.20.1 and 1.20.2 diff at https://github.dev/extremeheat/extracted_minecraft_data/pull/5

**Comment by extremeheat** [comment]
done in https://github.com/PrismarineJS/minecraft-data/pull/812
