### ISSUE TITLE
PC version 0.30c confusing

### ISSUE THREAD

**Issue by PonasKovas** [PrismarineJS/minecraft-data#914]
Hello, I am generating some stuff from this data but the 0.30c version having `version: 7` in `version.json` is fucking things up for me because I assume that that is the [14w04a](https://minecraft.wiki/w/14w04a) version which also has protocol version 7.

Why is the 0.30c version even here? There are no other versions below 1.7, who even cares about classic?

Can 0.30c be removed from this repository completely? I can make a PR if you will merge it.

**Comment by PonasKovas** [comment]
can you add something like `classic: true` to it's version.json or something then? because how can i tell that its not from the same versioning scheme as literally all other versions in that directory, without hardcoding a list...

**Comment by extremeheat** [comment]
The pc/common/protocolversions.json list doesn't list classic.
