### ISSUE TITLE
Light emitting values of blocks

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/minecraft-data#96]
@hansihe was saying in #mcdevs that http://minecraft.gamepedia.com/Light#Light-emitting_blocks are interesting values
Possibilities:
* putting it in blocks.json, but it would mean expanding the extractor https://github.com/PrismarineJS/minecraft-wiki-extractor/blob/master/lib/block_extractor.js again
* putting it in a blocks_lights.json because it's kind of separate from most uses of blocks

(it would anyway be exposed as a single block thing in wrappers)

**Comment by rom1504** [comment]
A benefit of blocks_lights.json is it could be written manually to begin with ;)

**Comment by rom1504** [comment]
fixed by #102

**Comment by nickelpro** [comment]
Right now light emitting blocks such as lava are listed as "transparent" when that's not really true. They're opaque light emitters in their own right, not transparent to the light level above them.

**Comment by rom1504** [comment]
Hmm the wiki do list lava as transparent http://minecraft.gamepedia.com/Lava

@hansihe how would you handle lava in your light handling thing ?

(also see WIP in https://github.com/PrismarineJS/minecraft-wiki-extractor/issues/12 )

**Comment by hansihe** [comment]
I do think what @nickelpro is saying is technically true, but I don't think it realistically matters since lava emits the highest possible light level, 15.

**Comment by hansihe** [comment]
Lava would be handled just like a normal light emitting block. Since light emitters don't affect blocks that are lit up to a higher light level by another light emitter, and lava emits the highest possible light level, 15, I don't think there is any possible way changing the filterlight of lava would make any difference.

**Comment by Gjum** [comment]
This could be verified by creating a closed room with only lava (/glowstone/redstone lamps) as walls and looking at the skylight in the F3 screen.

**Comment by hansihe** [comment]
@Gjum has a point, what I said earlier was false. If I'm not mistaken, the filterlight value of lava would in fact affect skylight.
