### ISSUE TITLE
Add other users to README

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/minecraft-data#97]
* https://github.com/hansihe/McEx : investigate what data is used
* https://github.com/oldmanmike/opensandbox/commit/14fa9b5a0430627652d19a4d2abc3184f2663caf : looks very much like mcdata schema, is data used yet ?

**Comment by rom1504** [comment]
https://github.com/hansihe/McEx/blob/8be2b594b63273bc5593904db28e47e3a84b6ca5/lib/values/blocks.ex

**Comment by rom1504** [comment]
I added McEx.

opensandbox doesn't seem to use the data yet.

**Comment by oldmanmike** [comment]
Yeah, right now I'm intending on using it, but I haven't gotten around to writing the JSON serialization code yet.
