### ISSUE TITLE
Auto updater

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/minecraft-data#98]
Most of the data the minecraft-data is automatically extracted from the mcwiki (and wiki.vg)

It would be nice to make a bot that would automatically create PR when stuff change on the wiki.
A bit like http://greenkeeper.io/

**Comment by Gjum** [comment]
I really like this idea of a bot that allows other bots to update other bots.

![I make tools for managing job-hunting sites for people who make tools for managing job-hunting sites for people who make tools for ...](http://imgs.xkcd.com/comics/tools.png)

**Comment by rom1504** [comment]
I don't think wikis have a push api no. Would have to look if there are new revisions after a stored date (possibly by using the [watchlist](http://wiki.vg/Special:Watchlist) or [recentchanges](http://wiki.vg/Special:RecentChanges) to help), or you know, just run the extraction every hour and check if resulting files have changed.

**Comment by rom1504** [comment]
Ohh there's https://www.mediawiki.org/wiki/Manual:Hooks . Maybe it can be used, got to check how much permission you need to use that.

**Comment by Gjum** [comment]
For polling, watchlist of a custom account is probably the best.

For hooks, a wiki admin would have to add some php, which might work for wiki.vg, but probably not for mcwiki. We can still ask though.

**Comment by rom1504** [comment]
Yeah watchlist is probably easier.

**Comment by rom1504** [comment]
> 16:35 < Botched> [VERSION] Minecraft Snapshot 16w07b has been released!

heh, if we had good jar extractors, we could extract data automatically right when a new version is out !

**Comment by Gjum** [comment]
hoping for https://github.com/Pokechu22/Burger

**Comment by rom1504** [comment]
https://circleci.com/docs/1.0/nightly-builds/ could be used to run a circle ci build to do stuff like https://github.com/rom1504/minecraft-assets/issues/1 using https://launchermeta.mojang.com/mc/game/version_manifest.json

**Comment by rom1504** [comment]
mostly done at https://github.com/PrismarineJS/minecraft-data/blob/master/doc/add-data-new-version.md + https://github.com/PrismarineJS/minecraft-data-auto-updater
